version: '3'
services:

### rabbitMQ
  rabbit-mq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"


### postgres/storage/config        
  storage-db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarty
      
### redis      
  redis:
    image: "redis"
    ports:
        - '6379:6379'