spring:

  profiles:
    active: default
    
  rabbitmq:
    addresses: "localhost"
    
  datasource:
    url: jdbc:postgresql://localhost:5432/smarty
    username: postgres
    password: postgres
    initialization-mode: always

server:
  port: 8882

logging:
  level: 
    root: INFO
