spring:

  profiles:
    active: default
    
  rabbitmq:
    addresses: "rabbit-mq"

  redis:
    host: redis
    port: 6379

  datasource:
    url: jdbc:postgresql://storage-db:5432/smarty
    username: postgres
    password: postgres
    initialization-mode: always
    
  liquibase:
    enabled: true

server:
  port: 8882

logging:
  level: 
    root: INFO
