spring:
  profiles:
    active: default
  rabbitmq:
    addresses: "localhost"

server:
  port: 8881

logging:
  level: 
    root: INFO
    
mqtt:
  uri: tcp://192.168.112.71:1883
  client-id: smarty-local
