server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:postgresql://localhost:5432/smarty
    username: postgres
    password: postgres
    initialization-mode: always
    
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    
# Logging configuration print only messages for tutorial purposes
logging:
  level:
    org:
      springframework:
        security: INFO
